version: '3.5'
services:
  mysqldb:
    image: "mysql:latest"
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: x-financial-arbitration
      MYSQL_USER: worker
      MYSQL_PASSWORD: worker
    networks:
      - db-net
  worker:
    build: .
    environment:
      NODE_CONFIG_DIR: ./src/config
      COLLECT_ONLY_MATCHES: "true"
      NODE_ENV: development
      DB_NAME: x-financial-arbitration
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: worker
      DB_PASSWORD: worker
    networks:
      - db-net
    links:
      - mysqldb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysqldb
volumes:
  db_data:
networks:
  db-net:
    name: bittrex-db-net
